apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devsu-readonly
  namespace: devsu
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devsu-readonly-binding
  namespace: devsu
subjects:
- kind: User
  name: kind-kind
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devsu-readonly
  apiGroup: rbac.authorization.k8s.io
